// Mocks generated by Mockito 5.4.2 from annotations
// in appserap/test/widget/home/home.view_turno_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i25;

import 'package:appserap/database/app.database.dart' as _i10;
import 'package:appserap/database/daos/alternativa.dao.dart' as _i15;
import 'package:appserap/database/daos/arquivo.dao.dart' as _i16;
import 'package:appserap/database/daos/arquivo_audio.dao.dart' as _i12;
import 'package:appserap/database/daos/arquivo_video.dao.dart' as _i11;
import 'package:appserap/database/daos/contexto_prova.dao.dart' as _i17;
import 'package:appserap/database/daos/download_prova.dao.dart' as _i13;
import 'package:appserap/database/daos/jobs.dao.dart' as _i22;
import 'package:appserap/database/daos/prova.dao.dart' as _i18;
import 'package:appserap/database/daos/prova_aluno.dao.dart' as _i19;
import 'package:appserap/database/daos/prova_caderno.dao.dart' as _i20;
import 'package:appserap/database/daos/prova_questao_alternativa.dao.dart'
    as _i23;
import 'package:appserap/database/daos/questao.dao.dart' as _i14;
import 'package:appserap/database/daos/questao_arquivo.dao.dart' as _i21;
import 'package:appserap/services/api.dart' as _i3;
import 'package:appserap/services/rest/admin.service.dart' as _i5;
import 'package:appserap/services/rest/auth.admin.service.dart' as _i6;
import 'package:appserap/services/rest/usuario.service.dart' as _i4;
import 'package:appserap/stores/principal.store.dart' as _i26;
import 'package:appserap/stores/usuario.store.dart' as _i7;
import 'package:chopper/chopper.dart' as _i2;
import 'package:drift/drift.dart' as _i9;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i24;
import 'package:mobx/mobx.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i27;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChopperClient_0 extends _i1.SmartFake implements _i2.ChopperClient {
  _FakeChopperClient_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutenticacaoService_1 extends _i1.SmartFake
    implements _i3.AutenticacaoService {
  _FakeAutenticacaoService_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaService_2 extends _i1.SmartFake implements _i3.ProvaService {
  _FakeProvaService_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoService_3 extends _i1.SmartFake
    implements _i3.QuestaoService {
  _FakeQuestaoService_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlternativaService_4 extends _i1.SmartFake
    implements _i3.AlternativaService {
  _FakeAlternativaService_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivoService_5 extends _i1.SmartFake
    implements _i3.ArquivoService {
  _FakeArquivoService_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVersaoService_6 extends _i1.SmartFake implements _i3.VersaoService {
  _FakeVersaoService_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoRespostaService_7 extends _i1.SmartFake
    implements _i3.QuestaoRespostaService {
  _FakeQuestaoRespostaService_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsuarioService_8 extends _i1.SmartFake
    implements _i4.UsuarioService {
  _FakeUsuarioService_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeOrientacaoInicialService_9 extends _i1.SmartFake
    implements _i3.OrientacaoInicialService {
  _FakeOrientacaoInicialService_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextoProvaService_10 extends _i1.SmartFake
    implements _i3.ContextoProvaService {
  _FakeContextoProvaService_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadService_11 extends _i1.SmartFake
    implements _i3.DownloadService {
  _FakeDownloadService_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAdminService_12 extends _i1.SmartFake implements _i5.AdminService {
  _FakeAdminService_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAutenticacaoAdminService_13 extends _i1.SmartFake
    implements _i6.AutenticacaoAdminService {
  _FakeAutenticacaoAdminService_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeLogService_14 extends _i1.SmartFake implements _i3.LogService {
  _FakeLogService_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfiguracaoService_15 extends _i1.SmartFake
    implements _i3.ConfiguracaoService {
  _FakeConfiguracaoService_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaResultadoService_16 extends _i1.SmartFake
    implements _i3.ProvaResultadoService {
  _FakeProvaResultadoService_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaTaiService_17 extends _i1.SmartFake
    implements _i3.ProvaTaiService {
  _FakeProvaTaiService_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUsuarioStore_18 extends _i1.SmartFake implements _i7.UsuarioStore {
  _FakeUsuarioStore_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_19 extends _i1.SmartFake
    implements _i8.ReactiveContext {
  _FakeReactiveContext_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_20 extends _i1.SmartFake
    implements _i9.MigrationStrategy {
  _FakeMigrationStrategy_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvasDbTable_21 extends _i1.SmartFake
    implements _i10.$ProvasDbTable {
  _Fake$ProvasDbTable_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$QuestoesDbTable_22 extends _i1.SmartFake
    implements _i10.$QuestoesDbTable {
  _Fake$QuestoesDbTable_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AlternativasDbTable_23 extends _i1.SmartFake
    implements _i10.$AlternativasDbTable {
  _Fake$AlternativasDbTable_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosDbTable_24 extends _i1.SmartFake
    implements _i10.$ArquivosDbTable {
  _Fake$ArquivosDbTable_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ContextosProvaDbTable_25 extends _i1.SmartFake
    implements _i10.$ContextosProvaDbTable {
  _Fake$ContextosProvaDbTable_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosVideoDbTable_26 extends _i1.SmartFake
    implements _i10.$ArquivosVideoDbTable {
  _Fake$ArquivosVideoDbTable_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosAudioDbTable_27 extends _i1.SmartFake
    implements _i10.$ArquivosAudioDbTable {
  _Fake$ArquivosAudioDbTable_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$DownloadProvasDbTable_28 extends _i1.SmartFake
    implements _i10.$DownloadProvasDbTable {
  _Fake$DownloadProvasDbTable_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaAlunoTableTable_29 extends _i1.SmartFake
    implements _i10.$ProvaAlunoTableTable {
  _Fake$ProvaAlunoTableTable_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaCadernoTableTable_30 extends _i1.SmartFake
    implements _i10.$ProvaCadernoTableTable {
  _Fake$ProvaCadernoTableTable_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$QuestaoArquivoTableTable_31 extends _i1.SmartFake
    implements _i10.$QuestaoArquivoTableTable {
  _Fake$QuestaoArquivoTableTable_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$JobsTableTable_32 extends _i1.SmartFake
    implements _i10.$JobsTableTable {
  _Fake$JobsTableTable_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaQuestaoAlternativaTableTable_33 extends _i1.SmartFake
    implements _i10.$ProvaQuestaoAlternativaTableTable {
  _Fake$ProvaQuestaoAlternativaTableTable_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivosVideosDao_34 extends _i1.SmartFake
    implements _i11.ArquivosVideosDao {
  _FakeArquivosVideosDao_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivosAudioDao_35 extends _i1.SmartFake
    implements _i12.ArquivosAudioDao {
  _FakeArquivosAudioDao_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadProvaDao_36 extends _i1.SmartFake
    implements _i13.DownloadProvaDao {
  _FakeDownloadProvaDao_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoDao_37 extends _i1.SmartFake implements _i14.QuestaoDao {
  _FakeQuestaoDao_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlternativaDao_38 extends _i1.SmartFake
    implements _i15.AlternativaDao {
  _FakeAlternativaDao_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivoDao_39 extends _i1.SmartFake implements _i16.ArquivoDao {
  _FakeArquivoDao_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextoProvaDao_40 extends _i1.SmartFake
    implements _i17.ContextoProvaDao {
  _FakeContextoProvaDao_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaDao_41 extends _i1.SmartFake implements _i18.ProvaDao {
  _FakeProvaDao_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaAlunoDao_42 extends _i1.SmartFake
    implements _i19.ProvaAlunoDao {
  _FakeProvaAlunoDao_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaCadernoDao_43 extends _i1.SmartFake
    implements _i20.ProvaCadernoDao {
  _FakeProvaCadernoDao_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoArquivoDao_44 extends _i1.SmartFake
    implements _i21.QuestaoArquivoDao {
  _FakeQuestaoArquivoDao_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobDao_45 extends _i1.SmartFake implements _i22.JobDao {
  _FakeJobDao_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaQuestaoAlternativaDao_46 extends _i1.SmartFake
    implements _i23.ProvaQuestaoAlternativaDao {
  _FakeProvaQuestaoAlternativaDao_46(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_47 extends _i1.SmartFake
    implements _i9.GeneratedDatabase {
  _FakeGeneratedDatabase_47(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_48 extends _i1.SmartFake
    implements _i9.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_48(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_49 extends _i1.SmartFake
    implements _i9.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_49(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_50 extends _i1.SmartFake
    implements _i9.DatabaseConnection {
  _FakeDatabaseConnection_50(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSqlTypes_51 extends _i1.SmartFake implements _i9.SqlTypes {
  _FakeSqlTypes_51(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_52 extends _i1.SmartFake implements _i9.QueryExecutor {
  _FakeQueryExecutor_52(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_53 extends _i1.SmartFake
    implements _i24.StreamQueryStore {
  _FakeStreamQueryStore_53(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_54 extends _i1.SmartFake
    implements _i9.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_54(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_55 extends _i1.SmartFake implements _i9.Migrator {
  _FakeMigrator_55(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_56<T1> extends _i1.SmartFake implements _i25.Future<T1> {
  _FakeFuture_56(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_57<T1 extends _i9.Table, D1> extends _i1.SmartFake
    implements _i9.InsertStatement<T1, D1> {
  _FakeInsertStatement_57(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_58<T extends _i9.Table, D> extends _i1.SmartFake
    implements _i9.UpdateStatement<T, D> {
  _FakeUpdateStatement_58(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_59<T1 extends _i9.HasResultSet, D>
    extends _i1.SmartFake implements _i9.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_59(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_60<FirstT extends _i9.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i9.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_60(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_61<T1 extends _i9.Table, D1> extends _i1.SmartFake
    implements _i9.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_61(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_62<T> extends _i1.SmartFake implements _i9.Selectable<T> {
  _FakeSelectable_62(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_63 extends _i1.SmartFake
    implements _i9.GenerationContext {
  _FakeGenerationContext_63(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i3.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ChopperClient get chopper => (super.noSuchMethod(
        Invocation.getter(#chopper),
        returnValue: _FakeChopperClient_0(
          this,
          Invocation.getter(#chopper),
        ),
      ) as _i2.ChopperClient);
  @override
  _i3.AutenticacaoService get auth => (super.noSuchMethod(
        Invocation.getter(#auth),
        returnValue: _FakeAutenticacaoService_1(
          this,
          Invocation.getter(#auth),
        ),
      ) as _i3.AutenticacaoService);
  @override
  _i3.ProvaService get prova => (super.noSuchMethod(
        Invocation.getter(#prova),
        returnValue: _FakeProvaService_2(
          this,
          Invocation.getter(#prova),
        ),
      ) as _i3.ProvaService);
  @override
  _i3.QuestaoService get questao => (super.noSuchMethod(
        Invocation.getter(#questao),
        returnValue: _FakeQuestaoService_3(
          this,
          Invocation.getter(#questao),
        ),
      ) as _i3.QuestaoService);
  @override
  _i3.AlternativaService get alternativa => (super.noSuchMethod(
        Invocation.getter(#alternativa),
        returnValue: _FakeAlternativaService_4(
          this,
          Invocation.getter(#alternativa),
        ),
      ) as _i3.AlternativaService);
  @override
  _i3.ArquivoService get arquivo => (super.noSuchMethod(
        Invocation.getter(#arquivo),
        returnValue: _FakeArquivoService_5(
          this,
          Invocation.getter(#arquivo),
        ),
      ) as _i3.ArquivoService);
  @override
  _i3.VersaoService get versao => (super.noSuchMethod(
        Invocation.getter(#versao),
        returnValue: _FakeVersaoService_6(
          this,
          Invocation.getter(#versao),
        ),
      ) as _i3.VersaoService);
  @override
  _i3.QuestaoRespostaService get questaoResposta => (super.noSuchMethod(
        Invocation.getter(#questaoResposta),
        returnValue: _FakeQuestaoRespostaService_7(
          this,
          Invocation.getter(#questaoResposta),
        ),
      ) as _i3.QuestaoRespostaService);
  @override
  _i4.UsuarioService get usuario => (super.noSuchMethod(
        Invocation.getter(#usuario),
        returnValue: _FakeUsuarioService_8(
          this,
          Invocation.getter(#usuario),
        ),
      ) as _i4.UsuarioService);
  @override
  _i3.OrientacaoInicialService get orientacoesIniciais => (super.noSuchMethod(
        Invocation.getter(#orientacoesIniciais),
        returnValue: _FakeOrientacaoInicialService_9(
          this,
          Invocation.getter(#orientacoesIniciais),
        ),
      ) as _i3.OrientacaoInicialService);
  @override
  _i3.ContextoProvaService get contextoProva => (super.noSuchMethod(
        Invocation.getter(#contextoProva),
        returnValue: _FakeContextoProvaService_10(
          this,
          Invocation.getter(#contextoProva),
        ),
      ) as _i3.ContextoProvaService);
  @override
  _i3.DownloadService get download => (super.noSuchMethod(
        Invocation.getter(#download),
        returnValue: _FakeDownloadService_11(
          this,
          Invocation.getter(#download),
        ),
      ) as _i3.DownloadService);
  @override
  _i5.AdminService get admin => (super.noSuchMethod(
        Invocation.getter(#admin),
        returnValue: _FakeAdminService_12(
          this,
          Invocation.getter(#admin),
        ),
      ) as _i5.AdminService);
  @override
  _i6.AutenticacaoAdminService get adminAuth => (super.noSuchMethod(
        Invocation.getter(#adminAuth),
        returnValue: _FakeAutenticacaoAdminService_13(
          this,
          Invocation.getter(#adminAuth),
        ),
      ) as _i6.AutenticacaoAdminService);
  @override
  _i3.LogService get log => (super.noSuchMethod(
        Invocation.getter(#log),
        returnValue: _FakeLogService_14(
          this,
          Invocation.getter(#log),
        ),
      ) as _i3.LogService);
  @override
  _i3.ConfiguracaoService get configuracao => (super.noSuchMethod(
        Invocation.getter(#configuracao),
        returnValue: _FakeConfiguracaoService_15(
          this,
          Invocation.getter(#configuracao),
        ),
      ) as _i3.ConfiguracaoService);
  @override
  _i3.ProvaResultadoService get provaResultado => (super.noSuchMethod(
        Invocation.getter(#provaResultado),
        returnValue: _FakeProvaResultadoService_16(
          this,
          Invocation.getter(#provaResultado),
        ),
      ) as _i3.ProvaResultadoService);
  @override
  _i3.ProvaTaiService get provaTai => (super.noSuchMethod(
        Invocation.getter(#provaTai),
        returnValue: _FakeProvaTaiService_17(
          this,
          Invocation.getter(#provaTai),
        ),
      ) as _i3.ProvaTaiService);
}

/// A class which mocks [PrincipalStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrincipalStore extends _i1.Mock implements _i26.PrincipalStore {
  MockPrincipalStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.UsuarioStore get usuario => (super.noSuchMethod(
        Invocation.getter(#usuario),
        returnValue: _FakeUsuarioStore_18(
          this,
          Invocation.getter(#usuario),
        ),
      ) as _i7.UsuarioStore);
  @override
  String get dispositivoId => (super.noSuchMethod(
        Invocation.getter(#dispositivoId),
        returnValue: '',
      ) as String);
  @override
  set dispositivoId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #dispositivoId,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get idDispositivo => (super.noSuchMethod(
        Invocation.getter(#idDispositivo),
        returnValue: '',
      ) as String);
  @override
  set idDispositivo(String? value) => super.noSuchMethod(
        Invocation.setter(
          #idDispositivo,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get versaoApp => (super.noSuchMethod(
        Invocation.getter(#versaoApp),
        returnValue: '',
      ) as String);
  @override
  set versaoApp(String? value) => super.noSuchMethod(
        Invocation.setter(
          #versaoApp,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get temConexao => (super.noSuchMethod(
        Invocation.getter(#temConexao),
        returnValue: false,
      ) as bool);
  @override
  set temConexao(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #temConexao,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get versao => (super.noSuchMethod(
        Invocation.getter(#versao),
        returnValue: '',
      ) as String);
  @override
  _i8.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_19(
          this,
          Invocation.getter(#context),
        ),
      ) as _i8.ReactiveContext);
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get shout => (super.noSuchMethod(
        Invocation.getter(#shout),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get severe => (super.noSuchMethod(
        Invocation.getter(#severe),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get warning => (super.noSuchMethod(
        Invocation.getter(#warning),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get fine => (super.noSuchMethod(
        Invocation.getter(#fine),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get finer => (super.noSuchMethod(
        Invocation.getter(#finer),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get finest => (super.noSuchMethod(
        Invocation.getter(#finest),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  _i25.Future<void> setup() => (super.noSuchMethod(
        Invocation.method(
          #setup,
          [],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i25.Future<String?> obetIdDispositivo() => (super.noSuchMethod(
        Invocation.method(
          #obetIdDispositivo,
          [],
        ),
        returnValue: _i25.Future<String?>.value(),
      ) as _i25.Future<String?>);
  @override
  _i25.Future<void> obterVersaoDoApp() => (super.noSuchMethod(
        Invocation.method(
          #obterVersaoDoApp,
          [],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  _i25.Future<void> sair() => (super.noSuchMethod(
        Invocation.method(
          #sair,
          [],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i10.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);
  @override
  _i9.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_20(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i9.MigrationStrategy);
  @override
  _i10.$ProvasDbTable get provasDb => (super.noSuchMethod(
        Invocation.getter(#provasDb),
        returnValue: _Fake$ProvasDbTable_21(
          this,
          Invocation.getter(#provasDb),
        ),
      ) as _i10.$ProvasDbTable);
  @override
  _i10.$QuestoesDbTable get questoesDb => (super.noSuchMethod(
        Invocation.getter(#questoesDb),
        returnValue: _Fake$QuestoesDbTable_22(
          this,
          Invocation.getter(#questoesDb),
        ),
      ) as _i10.$QuestoesDbTable);
  @override
  _i10.$AlternativasDbTable get alternativasDb => (super.noSuchMethod(
        Invocation.getter(#alternativasDb),
        returnValue: _Fake$AlternativasDbTable_23(
          this,
          Invocation.getter(#alternativasDb),
        ),
      ) as _i10.$AlternativasDbTable);
  @override
  _i10.$ArquivosDbTable get arquivosDb => (super.noSuchMethod(
        Invocation.getter(#arquivosDb),
        returnValue: _Fake$ArquivosDbTable_24(
          this,
          Invocation.getter(#arquivosDb),
        ),
      ) as _i10.$ArquivosDbTable);
  @override
  _i10.$ContextosProvaDbTable get contextosProvaDb => (super.noSuchMethod(
        Invocation.getter(#contextosProvaDb),
        returnValue: _Fake$ContextosProvaDbTable_25(
          this,
          Invocation.getter(#contextosProvaDb),
        ),
      ) as _i10.$ContextosProvaDbTable);
  @override
  _i10.$ArquivosVideoDbTable get arquivosVideoDb => (super.noSuchMethod(
        Invocation.getter(#arquivosVideoDb),
        returnValue: _Fake$ArquivosVideoDbTable_26(
          this,
          Invocation.getter(#arquivosVideoDb),
        ),
      ) as _i10.$ArquivosVideoDbTable);
  @override
  _i10.$ArquivosAudioDbTable get arquivosAudioDb => (super.noSuchMethod(
        Invocation.getter(#arquivosAudioDb),
        returnValue: _Fake$ArquivosAudioDbTable_27(
          this,
          Invocation.getter(#arquivosAudioDb),
        ),
      ) as _i10.$ArquivosAudioDbTable);
  @override
  _i10.$DownloadProvasDbTable get downloadProvasDb => (super.noSuchMethod(
        Invocation.getter(#downloadProvasDb),
        returnValue: _Fake$DownloadProvasDbTable_28(
          this,
          Invocation.getter(#downloadProvasDb),
        ),
      ) as _i10.$DownloadProvasDbTable);
  @override
  _i10.$ProvaAlunoTableTable get provaAlunoTable => (super.noSuchMethod(
        Invocation.getter(#provaAlunoTable),
        returnValue: _Fake$ProvaAlunoTableTable_29(
          this,
          Invocation.getter(#provaAlunoTable),
        ),
      ) as _i10.$ProvaAlunoTableTable);
  @override
  _i10.$ProvaCadernoTableTable get provaCadernoTable => (super.noSuchMethod(
        Invocation.getter(#provaCadernoTable),
        returnValue: _Fake$ProvaCadernoTableTable_30(
          this,
          Invocation.getter(#provaCadernoTable),
        ),
      ) as _i10.$ProvaCadernoTableTable);
  @override
  _i10.$QuestaoArquivoTableTable get questaoArquivoTable => (super.noSuchMethod(
        Invocation.getter(#questaoArquivoTable),
        returnValue: _Fake$QuestaoArquivoTableTable_31(
          this,
          Invocation.getter(#questaoArquivoTable),
        ),
      ) as _i10.$QuestaoArquivoTableTable);
  @override
  _i10.$JobsTableTable get jobsTable => (super.noSuchMethod(
        Invocation.getter(#jobsTable),
        returnValue: _Fake$JobsTableTable_32(
          this,
          Invocation.getter(#jobsTable),
        ),
      ) as _i10.$JobsTableTable);
  @override
  _i10.$ProvaQuestaoAlternativaTableTable get provaQuestaoAlternativaTable =>
      (super.noSuchMethod(
        Invocation.getter(#provaQuestaoAlternativaTable),
        returnValue: _Fake$ProvaQuestaoAlternativaTableTable_33(
          this,
          Invocation.getter(#provaQuestaoAlternativaTable),
        ),
      ) as _i10.$ProvaQuestaoAlternativaTableTable);
  @override
  _i11.ArquivosVideosDao get arquivosVideosDao => (super.noSuchMethod(
        Invocation.getter(#arquivosVideosDao),
        returnValue: _FakeArquivosVideosDao_34(
          this,
          Invocation.getter(#arquivosVideosDao),
        ),
      ) as _i11.ArquivosVideosDao);
  @override
  _i12.ArquivosAudioDao get arquivosAudioDao => (super.noSuchMethod(
        Invocation.getter(#arquivosAudioDao),
        returnValue: _FakeArquivosAudioDao_35(
          this,
          Invocation.getter(#arquivosAudioDao),
        ),
      ) as _i12.ArquivosAudioDao);
  @override
  _i13.DownloadProvaDao get downloadProvaDao => (super.noSuchMethod(
        Invocation.getter(#downloadProvaDao),
        returnValue: _FakeDownloadProvaDao_36(
          this,
          Invocation.getter(#downloadProvaDao),
        ),
      ) as _i13.DownloadProvaDao);
  @override
  _i14.QuestaoDao get questaoDao => (super.noSuchMethod(
        Invocation.getter(#questaoDao),
        returnValue: _FakeQuestaoDao_37(
          this,
          Invocation.getter(#questaoDao),
        ),
      ) as _i14.QuestaoDao);
  @override
  _i15.AlternativaDao get alternativaDao => (super.noSuchMethod(
        Invocation.getter(#alternativaDao),
        returnValue: _FakeAlternativaDao_38(
          this,
          Invocation.getter(#alternativaDao),
        ),
      ) as _i15.AlternativaDao);
  @override
  _i16.ArquivoDao get arquivoDao => (super.noSuchMethod(
        Invocation.getter(#arquivoDao),
        returnValue: _FakeArquivoDao_39(
          this,
          Invocation.getter(#arquivoDao),
        ),
      ) as _i16.ArquivoDao);
  @override
  _i17.ContextoProvaDao get contextoProvaDao => (super.noSuchMethod(
        Invocation.getter(#contextoProvaDao),
        returnValue: _FakeContextoProvaDao_40(
          this,
          Invocation.getter(#contextoProvaDao),
        ),
      ) as _i17.ContextoProvaDao);
  @override
  _i18.ProvaDao get provaDao => (super.noSuchMethod(
        Invocation.getter(#provaDao),
        returnValue: _FakeProvaDao_41(
          this,
          Invocation.getter(#provaDao),
        ),
      ) as _i18.ProvaDao);
  @override
  _i19.ProvaAlunoDao get provaAlunoDao => (super.noSuchMethod(
        Invocation.getter(#provaAlunoDao),
        returnValue: _FakeProvaAlunoDao_42(
          this,
          Invocation.getter(#provaAlunoDao),
        ),
      ) as _i19.ProvaAlunoDao);
  @override
  _i20.ProvaCadernoDao get provaCadernoDao => (super.noSuchMethod(
        Invocation.getter(#provaCadernoDao),
        returnValue: _FakeProvaCadernoDao_43(
          this,
          Invocation.getter(#provaCadernoDao),
        ),
      ) as _i20.ProvaCadernoDao);
  @override
  _i21.QuestaoArquivoDao get questaoArquivoDao => (super.noSuchMethod(
        Invocation.getter(#questaoArquivoDao),
        returnValue: _FakeQuestaoArquivoDao_44(
          this,
          Invocation.getter(#questaoArquivoDao),
        ),
      ) as _i21.QuestaoArquivoDao);
  @override
  _i22.JobDao get jobDao => (super.noSuchMethod(
        Invocation.getter(#jobDao),
        returnValue: _FakeJobDao_45(
          this,
          Invocation.getter(#jobDao),
        ),
      ) as _i22.JobDao);
  @override
  _i23.ProvaQuestaoAlternativaDao get provaQuestaoAlternativaDao =>
      (super.noSuchMethod(
        Invocation.getter(#provaQuestaoAlternativaDao),
        returnValue: _FakeProvaQuestaoAlternativaDao_46(
          this,
          Invocation.getter(#provaQuestaoAlternativaDao),
        ),
      ) as _i23.ProvaQuestaoAlternativaDao);
  @override
  Iterable<_i9.TableInfo<_i9.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i9.TableInfo<_i9.Table, Object?>>[],
      ) as Iterable<_i9.TableInfo<_i9.Table, Object?>>);
  @override
  List<_i9.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i9.DatabaseSchemaEntity>[],
      ) as List<_i9.DatabaseSchemaEntity>);
  @override
  _i9.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_47(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i9.GeneratedDatabase);
  @override
  _i9.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_48(
          this,
          Invocation.getter(#options),
        ),
      ) as _i9.DriftDatabaseOptions);
  @override
  _i9.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_49(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i9.StreamQueryUpdateRules);
  @override
  _i9.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_50(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i9.DatabaseConnection);
  @override
  _i9.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _FakeSqlTypes_51(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i9.SqlTypes);
  @override
  _i9.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_52(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i9.QueryExecutor);
  @override
  _i24.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_53(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i24.StreamQueryStore);
  @override
  _i9.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_54(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i9.DatabaseConnectionUser);
  @override
  _i25.Future<dynamic> limpar() => (super.noSuchMethod(
        Invocation.method(
          #limpar,
          [],
        ),
        returnValue: _i25.Future<dynamic>.value(),
      ) as _i25.Future<dynamic>);
  @override
  _i25.Future<dynamic> limparBanco() => (super.noSuchMethod(
        Invocation.method(
          #limparBanco,
          [],
        ),
        returnValue: _i25.Future<dynamic>.value(),
      ) as _i25.Future<dynamic>);
  @override
  _i9.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_55(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i9.Migrator);
  @override
  _i25.Future<void> beforeOpen(
    _i9.QueryExecutor? executor,
    _i9.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  _i25.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  _i25.Stream<List<Map<String, Object?>>> createStream(
          _i24.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i25.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i25.Stream<List<Map<String, Object?>>>);
  @override
  T alias<T, D>(
    _i9.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i27.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);
  @override
  void markTablesUpdated(Iterable<_i9.TableInfo<_i9.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyUpdates(Set<_i9.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i25.Stream<Set<_i9.TableUpdate>> tableUpdates(
          [_i9.TableUpdateQuery? query = const _i9.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i25.Stream<Set<_i9.TableUpdate>>.empty(),
      ) as _i25.Stream<Set<_i9.TableUpdate>>);
  @override
  _i25.Future<T> doWhenOpened<T>(
          _i25.FutureOr<T> Function(_i9.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i27.ifNotNull(
              _i27.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i25.Future<T>.value(v),
            ) ??
            _FakeFuture_56<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i25.Future<T>);
  @override
  _i9.InsertStatement<T, D> into<T extends _i9.Table, D>(
          _i9.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_57<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i9.InsertStatement<T, D>);
  @override
  _i9.UpdateStatement<Tbl, R> update<Tbl extends _i9.Table, R>(
          _i9.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_58<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i9.UpdateStatement<Tbl, R>);
  @override
  _i9.SimpleSelectStatement<T, R> select<T extends _i9.HasResultSet, R>(
    _i9.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_59<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i9.SimpleSelectStatement<T, R>);
  @override
  _i9.JoinedSelectStatement<T, R> selectOnly<T extends _i9.HasResultSet, R>(
    _i9.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_60<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i9.JoinedSelectStatement<T, R>);
  @override
  _i9.DeleteStatement<T, D> delete<T extends _i9.Table, D>(
          _i9.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_61<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i9.DeleteStatement<T, D>);
  @override
  _i25.Future<int> customUpdate(
    String? query, {
    List<_i9.Variable<Object>>? variables = const [],
    Set<_i9.TableInfo<_i9.Table, dynamic>>? updates,
    _i9.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i25.Future<int>.value(0),
      ) as _i25.Future<int>);
  @override
  _i25.Future<int> customInsert(
    String? query, {
    List<_i9.Variable<Object>>? variables = const [],
    Set<_i9.TableInfo<_i9.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i25.Future<int>.value(0),
      ) as _i25.Future<int>);
  @override
  _i25.Future<List<_i9.QueryRow>> customWriteReturning(
    String? query, {
    List<_i9.Variable<Object>>? variables = const [],
    Set<_i9.TableInfo<_i9.Table, dynamic>>? updates,
    _i9.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i25.Future<List<_i9.QueryRow>>.value(<_i9.QueryRow>[]),
      ) as _i25.Future<List<_i9.QueryRow>>);
  @override
  _i9.Selectable<_i9.QueryRow> customSelect(
    String? query, {
    List<_i9.Variable<Object>>? variables = const [],
    Set<_i9.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_62<_i9.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i9.Selectable<_i9.QueryRow>);
  @override
  _i9.Selectable<_i9.QueryRow> customSelectQuery(
    String? query, {
    List<_i9.Variable<Object>>? variables = const [],
    Set<_i9.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_62<_i9.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i9.Selectable<_i9.QueryRow>);
  @override
  _i25.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  _i25.Future<T> transaction<T>(
    _i25.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i27.ifNotNull(
              _i27.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i25.Future<T>.value(v),
            ) ??
            _FakeFuture_56<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i25.Future<T>);
  @override
  _i25.Future<void> batch(
          _i25.FutureOr<void> Function(_i9.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i25.Future<void>.value(),
        returnValueForMissingStub: _i25.Future<void>.value(),
      ) as _i25.Future<void>);
  @override
  _i9.GenerationContext $write(
    _i9.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_63(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i9.GenerationContext);
  @override
  _i9.GenerationContext $writeInsertable(
    _i9.TableInfo<_i9.Table, dynamic>? table,
    _i9.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_63(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i9.GenerationContext);
  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: '',
      ) as String);
}
