// Mocks generated by Mockito 5.4.2 from annotations
// in appserap/test/widget/home/home.view_turno_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i20;

import 'package:appserap/database/app.database.dart' as _i5;
import 'package:appserap/database/daos/alternativa.dao.dart' as _i10;
import 'package:appserap/database/daos/arquivo.dao.dart' as _i11;
import 'package:appserap/database/daos/arquivo_audio.dao.dart' as _i7;
import 'package:appserap/database/daos/arquivo_video.dao.dart' as _i6;
import 'package:appserap/database/daos/contexto_prova.dao.dart' as _i12;
import 'package:appserap/database/daos/download_prova.dao.dart' as _i8;
import 'package:appserap/database/daos/jobs.dao.dart' as _i17;
import 'package:appserap/database/daos/prova.dao.dart' as _i13;
import 'package:appserap/database/daos/prova_aluno.dao.dart' as _i14;
import 'package:appserap/database/daos/prova_caderno.dao.dart' as _i15;
import 'package:appserap/database/daos/prova_questao_alternativa.dao.dart'
    as _i18;
import 'package:appserap/database/daos/questao.dao.dart' as _i9;
import 'package:appserap/database/daos/questao_arquivo.dao.dart' as _i16;
import 'package:appserap/services/api.dart' as _i21;
import 'package:appserap/stores/principal.store.dart' as _i22;
import 'package:appserap/stores/usuario.store.dart' as _i2;
import 'package:drift/drift.dart' as _i4;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i19;
import 'package:mobx/mobx.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i23;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUsuarioStore_0 extends _i1.SmartFake implements _i2.UsuarioStore {
  _FakeUsuarioStore_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeReactiveContext_1 extends _i1.SmartFake
    implements _i3.ReactiveContext {
  _FakeReactiveContext_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrationStrategy_2 extends _i1.SmartFake
    implements _i4.MigrationStrategy {
  _FakeMigrationStrategy_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvasDbTable_3 extends _i1.SmartFake
    implements _i5.$ProvasDbTable {
  _Fake$ProvasDbTable_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$QuestoesDbTable_4 extends _i1.SmartFake
    implements _i5.$QuestoesDbTable {
  _Fake$QuestoesDbTable_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$AlternativasDbTable_5 extends _i1.SmartFake
    implements _i5.$AlternativasDbTable {
  _Fake$AlternativasDbTable_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosDbTable_6 extends _i1.SmartFake
    implements _i5.$ArquivosDbTable {
  _Fake$ArquivosDbTable_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ContextosProvaDbTable_7 extends _i1.SmartFake
    implements _i5.$ContextosProvaDbTable {
  _Fake$ContextosProvaDbTable_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosVideoDbTable_8 extends _i1.SmartFake
    implements _i5.$ArquivosVideoDbTable {
  _Fake$ArquivosVideoDbTable_8(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ArquivosAudioDbTable_9 extends _i1.SmartFake
    implements _i5.$ArquivosAudioDbTable {
  _Fake$ArquivosAudioDbTable_9(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$DownloadProvasDbTable_10 extends _i1.SmartFake
    implements _i5.$DownloadProvasDbTable {
  _Fake$DownloadProvasDbTable_10(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaAlunoTableTable_11 extends _i1.SmartFake
    implements _i5.$ProvaAlunoTableTable {
  _Fake$ProvaAlunoTableTable_11(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaCadernoTableTable_12 extends _i1.SmartFake
    implements _i5.$ProvaCadernoTableTable {
  _Fake$ProvaCadernoTableTable_12(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$QuestaoArquivoTableTable_13 extends _i1.SmartFake
    implements _i5.$QuestaoArquivoTableTable {
  _Fake$QuestaoArquivoTableTable_13(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$JobsTableTable_14 extends _i1.SmartFake
    implements _i5.$JobsTableTable {
  _Fake$JobsTableTable_14(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _Fake$ProvaQuestaoAlternativaTableTable_15 extends _i1.SmartFake
    implements _i5.$ProvaQuestaoAlternativaTableTable {
  _Fake$ProvaQuestaoAlternativaTableTable_15(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivosVideosDao_16 extends _i1.SmartFake
    implements _i6.ArquivosVideosDao {
  _FakeArquivosVideosDao_16(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivosAudioDao_17 extends _i1.SmartFake
    implements _i7.ArquivosAudioDao {
  _FakeArquivosAudioDao_17(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDownloadProvaDao_18 extends _i1.SmartFake
    implements _i8.DownloadProvaDao {
  _FakeDownloadProvaDao_18(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoDao_19 extends _i1.SmartFake implements _i9.QuestaoDao {
  _FakeQuestaoDao_19(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAlternativaDao_20 extends _i1.SmartFake
    implements _i10.AlternativaDao {
  _FakeAlternativaDao_20(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeArquivoDao_21 extends _i1.SmartFake implements _i11.ArquivoDao {
  _FakeArquivoDao_21(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeContextoProvaDao_22 extends _i1.SmartFake
    implements _i12.ContextoProvaDao {
  _FakeContextoProvaDao_22(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaDao_23 extends _i1.SmartFake implements _i13.ProvaDao {
  _FakeProvaDao_23(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaAlunoDao_24 extends _i1.SmartFake
    implements _i14.ProvaAlunoDao {
  _FakeProvaAlunoDao_24(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaCadernoDao_25 extends _i1.SmartFake
    implements _i15.ProvaCadernoDao {
  _FakeProvaCadernoDao_25(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQuestaoArquivoDao_26 extends _i1.SmartFake
    implements _i16.QuestaoArquivoDao {
  _FakeQuestaoArquivoDao_26(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJobDao_27 extends _i1.SmartFake implements _i17.JobDao {
  _FakeJobDao_27(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProvaQuestaoAlternativaDao_28 extends _i1.SmartFake
    implements _i18.ProvaQuestaoAlternativaDao {
  _FakeProvaQuestaoAlternativaDao_28(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGeneratedDatabase_29 extends _i1.SmartFake
    implements _i4.GeneratedDatabase {
  _FakeGeneratedDatabase_29(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDriftDatabaseOptions_30 extends _i1.SmartFake
    implements _i4.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_30(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryUpdateRules_31 extends _i1.SmartFake
    implements _i4.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_31(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnection_32 extends _i1.SmartFake
    implements _i4.DatabaseConnection {
  _FakeDatabaseConnection_32(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSqlTypes_33 extends _i1.SmartFake implements _i4.SqlTypes {
  _FakeSqlTypes_33(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeQueryExecutor_34 extends _i1.SmartFake implements _i4.QueryExecutor {
  _FakeQueryExecutor_34(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeStreamQueryStore_35 extends _i1.SmartFake
    implements _i19.StreamQueryStore {
  _FakeStreamQueryStore_35(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseConnectionUser_36 extends _i1.SmartFake
    implements _i4.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_36(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMigrator_37 extends _i1.SmartFake implements _i4.Migrator {
  _FakeMigrator_37(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeFuture_38<T1> extends _i1.SmartFake implements _i20.Future<T1> {
  _FakeFuture_38(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInsertStatement_39<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.InsertStatement<T1, D1> {
  _FakeInsertStatement_39(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUpdateStatement_40<T extends _i4.Table, D> extends _i1.SmartFake
    implements _i4.UpdateStatement<T, D> {
  _FakeUpdateStatement_40(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSimpleSelectStatement_41<T1 extends _i4.HasResultSet, D>
    extends _i1.SmartFake implements _i4.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_41(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeJoinedSelectStatement_42<FirstT extends _i4.HasResultSet, FirstD>
    extends _i1.SmartFake implements _i4.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_42(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDeleteStatement_43<T1 extends _i4.Table, D1> extends _i1.SmartFake
    implements _i4.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_43(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeSelectable_44<T> extends _i1.SmartFake implements _i4.Selectable<T> {
  _FakeSelectable_44(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGenerationContext_45 extends _i1.SmartFake
    implements _i4.GenerationContext {
  _FakeGenerationContext_45(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i21.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [PrincipalStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockPrincipalStore extends _i1.Mock implements _i22.PrincipalStore {
  MockPrincipalStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.UsuarioStore get usuario => (super.noSuchMethod(
        Invocation.getter(#usuario),
        returnValue: _FakeUsuarioStore_0(
          this,
          Invocation.getter(#usuario),
        ),
      ) as _i2.UsuarioStore);
  @override
  String get dispositivoId => (super.noSuchMethod(
        Invocation.getter(#dispositivoId),
        returnValue: '',
      ) as String);
  @override
  set dispositivoId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #dispositivoId,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get idDispositivo => (super.noSuchMethod(
        Invocation.getter(#idDispositivo),
        returnValue: '',
      ) as String);
  @override
  set idDispositivo(String? value) => super.noSuchMethod(
        Invocation.setter(
          #idDispositivo,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get versaoApp => (super.noSuchMethod(
        Invocation.getter(#versaoApp),
        returnValue: '',
      ) as String);
  @override
  set versaoApp(String? value) => super.noSuchMethod(
        Invocation.setter(
          #versaoApp,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  bool get temConexao => (super.noSuchMethod(
        Invocation.getter(#temConexao),
        returnValue: false,
      ) as bool);
  @override
  set temConexao(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #temConexao,
          value,
        ),
        returnValueForMissingStub: null,
      );
  @override
  String get versao => (super.noSuchMethod(
        Invocation.getter(#versao),
        returnValue: '',
      ) as String);
  @override
  _i3.ReactiveContext get context => (super.noSuchMethod(
        Invocation.getter(#context),
        returnValue: _FakeReactiveContext_1(
          this,
          Invocation.getter(#context),
        ),
      ) as _i3.ReactiveContext);
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get shout => (super.noSuchMethod(
        Invocation.getter(#shout),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get severe => (super.noSuchMethod(
        Invocation.getter(#severe),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get warning => (super.noSuchMethod(
        Invocation.getter(#warning),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get info => (super.noSuchMethod(
        Invocation.getter(#info),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get config => (super.noSuchMethod(
        Invocation.getter(#config),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get fine => (super.noSuchMethod(
        Invocation.getter(#fine),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get finer => (super.noSuchMethod(
        Invocation.getter(#finer),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  void Function(
    Object?, [
    Object?,
    StackTrace?,
  ]) get finest => (super.noSuchMethod(
        Invocation.getter(#finest),
        returnValue: (
          Object? __p0, [
          Object? __p1,
          StackTrace? __p2,
        ]) {},
      ) as void Function(
        Object?, [
        Object?,
        StackTrace?,
      ]));
  @override
  _i20.Future<void> setup() => (super.noSuchMethod(
        Invocation.method(
          #setup,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i20.Future<String?> obetIdDispositivo() => (super.noSuchMethod(
        Invocation.method(
          #obetIdDispositivo,
          [],
        ),
        returnValue: _i20.Future<String?>.value(),
      ) as _i20.Future<String?>);
  @override
  _i20.Future<void> obterVersaoDoApp() => (super.noSuchMethod(
        Invocation.method(
          #obterVersaoDoApp,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  _i20.Future<void> sair() => (super.noSuchMethod(
        Invocation.method(
          #sair,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i5.AppDatabase {
  MockAppDatabase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  int get schemaVersion => (super.noSuchMethod(
        Invocation.getter(#schemaVersion),
        returnValue: 0,
      ) as int);
  @override
  _i4.MigrationStrategy get migration => (super.noSuchMethod(
        Invocation.getter(#migration),
        returnValue: _FakeMigrationStrategy_2(
          this,
          Invocation.getter(#migration),
        ),
      ) as _i4.MigrationStrategy);
  @override
  _i5.$ProvasDbTable get provasDb => (super.noSuchMethod(
        Invocation.getter(#provasDb),
        returnValue: _Fake$ProvasDbTable_3(
          this,
          Invocation.getter(#provasDb),
        ),
      ) as _i5.$ProvasDbTable);
  @override
  _i5.$QuestoesDbTable get questoesDb => (super.noSuchMethod(
        Invocation.getter(#questoesDb),
        returnValue: _Fake$QuestoesDbTable_4(
          this,
          Invocation.getter(#questoesDb),
        ),
      ) as _i5.$QuestoesDbTable);
  @override
  _i5.$AlternativasDbTable get alternativasDb => (super.noSuchMethod(
        Invocation.getter(#alternativasDb),
        returnValue: _Fake$AlternativasDbTable_5(
          this,
          Invocation.getter(#alternativasDb),
        ),
      ) as _i5.$AlternativasDbTable);
  @override
  _i5.$ArquivosDbTable get arquivosDb => (super.noSuchMethod(
        Invocation.getter(#arquivosDb),
        returnValue: _Fake$ArquivosDbTable_6(
          this,
          Invocation.getter(#arquivosDb),
        ),
      ) as _i5.$ArquivosDbTable);
  @override
  _i5.$ContextosProvaDbTable get contextosProvaDb => (super.noSuchMethod(
        Invocation.getter(#contextosProvaDb),
        returnValue: _Fake$ContextosProvaDbTable_7(
          this,
          Invocation.getter(#contextosProvaDb),
        ),
      ) as _i5.$ContextosProvaDbTable);
  @override
  _i5.$ArquivosVideoDbTable get arquivosVideoDb => (super.noSuchMethod(
        Invocation.getter(#arquivosVideoDb),
        returnValue: _Fake$ArquivosVideoDbTable_8(
          this,
          Invocation.getter(#arquivosVideoDb),
        ),
      ) as _i5.$ArquivosVideoDbTable);
  @override
  _i5.$ArquivosAudioDbTable get arquivosAudioDb => (super.noSuchMethod(
        Invocation.getter(#arquivosAudioDb),
        returnValue: _Fake$ArquivosAudioDbTable_9(
          this,
          Invocation.getter(#arquivosAudioDb),
        ),
      ) as _i5.$ArquivosAudioDbTable);
  @override
  _i5.$DownloadProvasDbTable get downloadProvasDb => (super.noSuchMethod(
        Invocation.getter(#downloadProvasDb),
        returnValue: _Fake$DownloadProvasDbTable_10(
          this,
          Invocation.getter(#downloadProvasDb),
        ),
      ) as _i5.$DownloadProvasDbTable);
  @override
  _i5.$ProvaAlunoTableTable get provaAlunoTable => (super.noSuchMethod(
        Invocation.getter(#provaAlunoTable),
        returnValue: _Fake$ProvaAlunoTableTable_11(
          this,
          Invocation.getter(#provaAlunoTable),
        ),
      ) as _i5.$ProvaAlunoTableTable);
  @override
  _i5.$ProvaCadernoTableTable get provaCadernoTable => (super.noSuchMethod(
        Invocation.getter(#provaCadernoTable),
        returnValue: _Fake$ProvaCadernoTableTable_12(
          this,
          Invocation.getter(#provaCadernoTable),
        ),
      ) as _i5.$ProvaCadernoTableTable);
  @override
  _i5.$QuestaoArquivoTableTable get questaoArquivoTable => (super.noSuchMethod(
        Invocation.getter(#questaoArquivoTable),
        returnValue: _Fake$QuestaoArquivoTableTable_13(
          this,
          Invocation.getter(#questaoArquivoTable),
        ),
      ) as _i5.$QuestaoArquivoTableTable);
  @override
  _i5.$JobsTableTable get jobsTable => (super.noSuchMethod(
        Invocation.getter(#jobsTable),
        returnValue: _Fake$JobsTableTable_14(
          this,
          Invocation.getter(#jobsTable),
        ),
      ) as _i5.$JobsTableTable);
  @override
  _i5.$ProvaQuestaoAlternativaTableTable get provaQuestaoAlternativaTable =>
      (super.noSuchMethod(
        Invocation.getter(#provaQuestaoAlternativaTable),
        returnValue: _Fake$ProvaQuestaoAlternativaTableTable_15(
          this,
          Invocation.getter(#provaQuestaoAlternativaTable),
        ),
      ) as _i5.$ProvaQuestaoAlternativaTableTable);
  @override
  _i6.ArquivosVideosDao get arquivosVideosDao => (super.noSuchMethod(
        Invocation.getter(#arquivosVideosDao),
        returnValue: _FakeArquivosVideosDao_16(
          this,
          Invocation.getter(#arquivosVideosDao),
        ),
      ) as _i6.ArquivosVideosDao);
  @override
  _i7.ArquivosAudioDao get arquivosAudioDao => (super.noSuchMethod(
        Invocation.getter(#arquivosAudioDao),
        returnValue: _FakeArquivosAudioDao_17(
          this,
          Invocation.getter(#arquivosAudioDao),
        ),
      ) as _i7.ArquivosAudioDao);
  @override
  _i8.DownloadProvaDao get downloadProvaDao => (super.noSuchMethod(
        Invocation.getter(#downloadProvaDao),
        returnValue: _FakeDownloadProvaDao_18(
          this,
          Invocation.getter(#downloadProvaDao),
        ),
      ) as _i8.DownloadProvaDao);
  @override
  _i9.QuestaoDao get questaoDao => (super.noSuchMethod(
        Invocation.getter(#questaoDao),
        returnValue: _FakeQuestaoDao_19(
          this,
          Invocation.getter(#questaoDao),
        ),
      ) as _i9.QuestaoDao);
  @override
  _i10.AlternativaDao get alternativaDao => (super.noSuchMethod(
        Invocation.getter(#alternativaDao),
        returnValue: _FakeAlternativaDao_20(
          this,
          Invocation.getter(#alternativaDao),
        ),
      ) as _i10.AlternativaDao);
  @override
  _i11.ArquivoDao get arquivoDao => (super.noSuchMethod(
        Invocation.getter(#arquivoDao),
        returnValue: _FakeArquivoDao_21(
          this,
          Invocation.getter(#arquivoDao),
        ),
      ) as _i11.ArquivoDao);
  @override
  _i12.ContextoProvaDao get contextoProvaDao => (super.noSuchMethod(
        Invocation.getter(#contextoProvaDao),
        returnValue: _FakeContextoProvaDao_22(
          this,
          Invocation.getter(#contextoProvaDao),
        ),
      ) as _i12.ContextoProvaDao);
  @override
  _i13.ProvaDao get provaDao => (super.noSuchMethod(
        Invocation.getter(#provaDao),
        returnValue: _FakeProvaDao_23(
          this,
          Invocation.getter(#provaDao),
        ),
      ) as _i13.ProvaDao);
  @override
  _i14.ProvaAlunoDao get provaAlunoDao => (super.noSuchMethod(
        Invocation.getter(#provaAlunoDao),
        returnValue: _FakeProvaAlunoDao_24(
          this,
          Invocation.getter(#provaAlunoDao),
        ),
      ) as _i14.ProvaAlunoDao);
  @override
  _i15.ProvaCadernoDao get provaCadernoDao => (super.noSuchMethod(
        Invocation.getter(#provaCadernoDao),
        returnValue: _FakeProvaCadernoDao_25(
          this,
          Invocation.getter(#provaCadernoDao),
        ),
      ) as _i15.ProvaCadernoDao);
  @override
  _i16.QuestaoArquivoDao get questaoArquivoDao => (super.noSuchMethod(
        Invocation.getter(#questaoArquivoDao),
        returnValue: _FakeQuestaoArquivoDao_26(
          this,
          Invocation.getter(#questaoArquivoDao),
        ),
      ) as _i16.QuestaoArquivoDao);
  @override
  _i17.JobDao get jobDao => (super.noSuchMethod(
        Invocation.getter(#jobDao),
        returnValue: _FakeJobDao_27(
          this,
          Invocation.getter(#jobDao),
        ),
      ) as _i17.JobDao);
  @override
  _i18.ProvaQuestaoAlternativaDao get provaQuestaoAlternativaDao =>
      (super.noSuchMethod(
        Invocation.getter(#provaQuestaoAlternativaDao),
        returnValue: _FakeProvaQuestaoAlternativaDao_28(
          this,
          Invocation.getter(#provaQuestaoAlternativaDao),
        ),
      ) as _i18.ProvaQuestaoAlternativaDao);
  @override
  Iterable<_i4.TableInfo<_i4.Table, Object?>> get allTables =>
      (super.noSuchMethod(
        Invocation.getter(#allTables),
        returnValue: <_i4.TableInfo<_i4.Table, Object?>>[],
      ) as Iterable<_i4.TableInfo<_i4.Table, Object?>>);
  @override
  List<_i4.DatabaseSchemaEntity> get allSchemaEntities => (super.noSuchMethod(
        Invocation.getter(#allSchemaEntities),
        returnValue: <_i4.DatabaseSchemaEntity>[],
      ) as List<_i4.DatabaseSchemaEntity>);
  @override
  _i4.GeneratedDatabase get attachedDatabase => (super.noSuchMethod(
        Invocation.getter(#attachedDatabase),
        returnValue: _FakeGeneratedDatabase_29(
          this,
          Invocation.getter(#attachedDatabase),
        ),
      ) as _i4.GeneratedDatabase);
  @override
  _i4.DriftDatabaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeDriftDatabaseOptions_30(
          this,
          Invocation.getter(#options),
        ),
      ) as _i4.DriftDatabaseOptions);
  @override
  _i4.StreamQueryUpdateRules get streamUpdateRules => (super.noSuchMethod(
        Invocation.getter(#streamUpdateRules),
        returnValue: _FakeStreamQueryUpdateRules_31(
          this,
          Invocation.getter(#streamUpdateRules),
        ),
      ) as _i4.StreamQueryUpdateRules);
  @override
  _i4.DatabaseConnection get connection => (super.noSuchMethod(
        Invocation.getter(#connection),
        returnValue: _FakeDatabaseConnection_32(
          this,
          Invocation.getter(#connection),
        ),
      ) as _i4.DatabaseConnection);
  @override
  _i4.SqlTypes get typeMapping => (super.noSuchMethod(
        Invocation.getter(#typeMapping),
        returnValue: _FakeSqlTypes_33(
          this,
          Invocation.getter(#typeMapping),
        ),
      ) as _i4.SqlTypes);
  @override
  _i4.QueryExecutor get executor => (super.noSuchMethod(
        Invocation.getter(#executor),
        returnValue: _FakeQueryExecutor_34(
          this,
          Invocation.getter(#executor),
        ),
      ) as _i4.QueryExecutor);
  @override
  _i19.StreamQueryStore get streamQueries => (super.noSuchMethod(
        Invocation.getter(#streamQueries),
        returnValue: _FakeStreamQueryStore_35(
          this,
          Invocation.getter(#streamQueries),
        ),
      ) as _i19.StreamQueryStore);
  @override
  _i4.DatabaseConnectionUser get resolvedEngine => (super.noSuchMethod(
        Invocation.getter(#resolvedEngine),
        returnValue: _FakeDatabaseConnectionUser_36(
          this,
          Invocation.getter(#resolvedEngine),
        ),
      ) as _i4.DatabaseConnectionUser);
  @override
  _i20.Future<dynamic> limpar() => (super.noSuchMethod(
        Invocation.method(
          #limpar,
          [],
        ),
        returnValue: _i20.Future<dynamic>.value(),
      ) as _i20.Future<dynamic>);
  @override
  _i20.Future<dynamic> limparBanco() => (super.noSuchMethod(
        Invocation.method(
          #limparBanco,
          [],
        ),
        returnValue: _i20.Future<dynamic>.value(),
      ) as _i20.Future<dynamic>);
  @override
  _i4.Migrator createMigrator() => (super.noSuchMethod(
        Invocation.method(
          #createMigrator,
          [],
        ),
        returnValue: _FakeMigrator_37(
          this,
          Invocation.method(
            #createMigrator,
            [],
          ),
        ),
      ) as _i4.Migrator);
  @override
  _i20.Future<void> beforeOpen(
    _i4.QueryExecutor? executor,
    _i4.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #beforeOpen,
          [
            executor,
            details,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  _i20.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  _i20.Stream<List<Map<String, Object?>>> createStream(
          _i19.QueryStreamFetcher? stmt) =>
      (super.noSuchMethod(
        Invocation.method(
          #createStream,
          [stmt],
        ),
        returnValue: _i20.Stream<List<Map<String, Object?>>>.empty(),
      ) as _i20.Stream<List<Map<String, Object?>>>);
  @override
  T alias<T, D>(
    _i4.ResultSetImplementation<T, D>? table,
    String? alias,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #alias,
          [
            table,
            alias,
          ],
        ),
        returnValue: _i23.dummyValue<T>(
          this,
          Invocation.method(
            #alias,
            [
              table,
              alias,
            ],
          ),
        ),
      ) as T);
  @override
  void markTablesUpdated(Iterable<_i4.TableInfo<_i4.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(
          #markTablesUpdated,
          [tables],
        ),
        returnValueForMissingStub: null,
      );
  @override
  void notifyUpdates(Set<_i4.TableUpdate>? updates) => super.noSuchMethod(
        Invocation.method(
          #notifyUpdates,
          [updates],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i20.Stream<Set<_i4.TableUpdate>> tableUpdates(
          [_i4.TableUpdateQuery? query = const _i4.TableUpdateQuery.any()]) =>
      (super.noSuchMethod(
        Invocation.method(
          #tableUpdates,
          [query],
        ),
        returnValue: _i20.Stream<Set<_i4.TableUpdate>>.empty(),
      ) as _i20.Stream<Set<_i4.TableUpdate>>);
  @override
  _i20.Future<T> doWhenOpened<T>(
          _i20.FutureOr<T> Function(_i4.QueryExecutor)? fn) =>
      (super.noSuchMethod(
        Invocation.method(
          #doWhenOpened,
          [fn],
        ),
        returnValue: _i23.ifNotNull(
              _i23.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #doWhenOpened,
                  [fn],
                ),
              ),
              (T v) => _i20.Future<T>.value(v),
            ) ??
            _FakeFuture_38<T>(
              this,
              Invocation.method(
                #doWhenOpened,
                [fn],
              ),
            ),
      ) as _i20.Future<T>);
  @override
  _i4.InsertStatement<T, D> into<T extends _i4.Table, D>(
          _i4.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #into,
          [table],
        ),
        returnValue: _FakeInsertStatement_39<T, D>(
          this,
          Invocation.method(
            #into,
            [table],
          ),
        ),
      ) as _i4.InsertStatement<T, D>);
  @override
  _i4.UpdateStatement<Tbl, R> update<Tbl extends _i4.Table, R>(
          _i4.TableInfo<Tbl, R>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [table],
        ),
        returnValue: _FakeUpdateStatement_40<Tbl, R>(
          this,
          Invocation.method(
            #update,
            [table],
          ),
        ),
      ) as _i4.UpdateStatement<Tbl, R>);
  @override
  _i4.SimpleSelectStatement<T, R> select<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #select,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeSimpleSelectStatement_41<T, R>(
          this,
          Invocation.method(
            #select,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i4.SimpleSelectStatement<T, R>);
  @override
  _i4.JoinedSelectStatement<T, R> selectOnly<T extends _i4.HasResultSet, R>(
    _i4.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #selectOnly,
          [table],
          {#distinct: distinct},
        ),
        returnValue: _FakeJoinedSelectStatement_42<T, R>(
          this,
          Invocation.method(
            #selectOnly,
            [table],
            {#distinct: distinct},
          ),
        ),
      ) as _i4.JoinedSelectStatement<T, R>);
  @override
  _i4.DeleteStatement<T, D> delete<T extends _i4.Table, D>(
          _i4.TableInfo<T, D>? table) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [table],
        ),
        returnValue: _FakeDeleteStatement_43<T, D>(
          this,
          Invocation.method(
            #delete,
            [table],
          ),
        ),
      ) as _i4.DeleteStatement<T, D>);
  @override
  _i20.Future<int> customUpdate(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.TableInfo<_i4.Table, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customUpdate,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i20.Future<int>.value(0),
      ) as _i20.Future<int>);
  @override
  _i20.Future<int> customInsert(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.TableInfo<_i4.Table, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customInsert,
          [query],
          {
            #variables: variables,
            #updates: updates,
          },
        ),
        returnValue: _i20.Future<int>.value(0),
      ) as _i20.Future<int>);
  @override
  _i20.Future<List<_i4.QueryRow>> customWriteReturning(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.TableInfo<_i4.Table, dynamic>>? updates,
    _i4.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customWriteReturning,
          [query],
          {
            #variables: variables,
            #updates: updates,
            #updateKind: updateKind,
          },
        ),
        returnValue: _i20.Future<List<_i4.QueryRow>>.value(<_i4.QueryRow>[]),
      ) as _i20.Future<List<_i4.QueryRow>>);
  @override
  _i4.Selectable<_i4.QueryRow> customSelect(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelect,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_44<_i4.QueryRow>(
          this,
          Invocation.method(
            #customSelect,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i4.Selectable<_i4.QueryRow>);
  @override
  _i4.Selectable<_i4.QueryRow> customSelectQuery(
    String? query, {
    List<_i4.Variable<Object>>? variables = const [],
    Set<_i4.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #customSelectQuery,
          [query],
          {
            #variables: variables,
            #readsFrom: readsFrom,
          },
        ),
        returnValue: _FakeSelectable_44<_i4.QueryRow>(
          this,
          Invocation.method(
            #customSelectQuery,
            [query],
            {
              #variables: variables,
              #readsFrom: readsFrom,
            },
          ),
        ),
      ) as _i4.Selectable<_i4.QueryRow>);
  @override
  _i20.Future<void> customStatement(
    String? statement, [
    List<dynamic>? args,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #customStatement,
          [
            statement,
            args,
          ],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  _i20.Future<T> transaction<T>(
    _i20.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #transaction,
          [action],
          {#requireNew: requireNew},
        ),
        returnValue: _i23.ifNotNull(
              _i23.dummyValueOrNull<T>(
                this,
                Invocation.method(
                  #transaction,
                  [action],
                  {#requireNew: requireNew},
                ),
              ),
              (T v) => _i20.Future<T>.value(v),
            ) ??
            _FakeFuture_38<T>(
              this,
              Invocation.method(
                #transaction,
                [action],
                {#requireNew: requireNew},
              ),
            ),
      ) as _i20.Future<T>);
  @override
  _i20.Future<void> batch(
          _i20.FutureOr<void> Function(_i4.Batch)? runInBatch) =>
      (super.noSuchMethod(
        Invocation.method(
          #batch,
          [runInBatch],
        ),
        returnValue: _i20.Future<void>.value(),
        returnValueForMissingStub: _i20.Future<void>.value(),
      ) as _i20.Future<void>);
  @override
  _i4.GenerationContext $write(
    _i4.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$write,
          [component],
          {
            #hasMultipleTables: hasMultipleTables,
            #startIndex: startIndex,
          },
        ),
        returnValue: _FakeGenerationContext_45(
          this,
          Invocation.method(
            #$write,
            [component],
            {
              #hasMultipleTables: hasMultipleTables,
              #startIndex: startIndex,
            },
          ),
        ),
      ) as _i4.GenerationContext);
  @override
  _i4.GenerationContext $writeInsertable(
    _i4.TableInfo<_i4.Table, dynamic>? table,
    _i4.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #$writeInsertable,
          [
            table,
            insertable,
          ],
          {#startIndex: startIndex},
        ),
        returnValue: _FakeGenerationContext_45(
          this,
          Invocation.method(
            #$writeInsertable,
            [
              table,
              insertable,
            ],
            {#startIndex: startIndex},
          ),
        ),
      ) as _i4.GenerationContext);
  @override
  String $expandVar(
    int? start,
    int? amount,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #$expandVar,
          [
            start,
            amount,
          ],
        ),
        returnValue: '',
      ) as String);
}
