FROM cirrusci/flutter:2.5.1 as build

WORKDIR /usr/src/app

COPY . .

RUN flutter pub get
RUN flutter pub run build_runner build --delete-conflicting-outputs
RUN flutter build web

FROM nginx:1.20.1-alpine

COPY default.conf /etc/nginx/conf.d/
COPY --from=build /usr/src/app/config /usr/share/nginx/html/config
COPY --from=build /usr/src/app/build/web /usr/share/nginx/html

EXPOSE 80
