FROM cirrusci/flutter:3.0.1 as build

WORKDIR /usr/src/app

COPY . .

RUN flutter pub get
RUN flutter build web --release

FROM nginx:1.20.1-alpine

COPY configuracoes/default.conf /etc/nginx/conf.d/
COPY --from=build /usr/src/app/config /usr/share/nginx/html/config
COPY --from=build /usr/src/app/build/web /usr/share/nginx/html

EXPOSE 80
