// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAZSHu4g-Kb5f1T-IAPtOYeKIqsS_2q2I',
    appId: '1:71333791813:web:c305c3a35e3abcae5cfb2c',
    messagingSenderId: '71333791813',
    projectId: 'dev-appserap',
    authDomain: 'dev-appserap.firebaseapp.com',
    storageBucket: 'dev-appserap.appspot.com',
    measurementId: 'G-2JYVT63SXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmB_N-D3laW8AUCwNgLw_390fIk6oW_Ys',
    appId: '1:71333791813:android:698ca2ef3e56f91c5cfb2c',
    messagingSenderId: '71333791813',
    projectId: 'dev-appserap',
    storageBucket: 'dev-appserap.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkli028iu79UBmBDlE-He92zbeUPX4COc',
    appId: '1:71333791813:ios:a100365f4c7360b15cfb2c',
    messagingSenderId: '71333791813',
    projectId: 'dev-appserap',
    storageBucket: 'dev-appserap.appspot.com',
    iosClientId: '71333791813-8pqg57pdd9uc0d7srfmj1ik63q235nkh.apps.googleusercontent.com',
    iosBundleId: 'br.gov.sp.prefeitura.sme.appserap.appserap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkli028iu79UBmBDlE-He92zbeUPX4COc',
    appId: '1:71333791813:ios:a100365f4c7360b15cfb2c',
    messagingSenderId: '71333791813',
    projectId: 'dev-appserap',
    storageBucket: 'dev-appserap.appspot.com',
    iosClientId: '71333791813-8pqg57pdd9uc0d7srfmj1ik63q235nkh.apps.googleusercontent.com',
    iosBundleId: 'br.gov.sp.prefeitura.sme.appserap.appserap',
  );
}
